### ISSUE TITLE
Where is the Agentclass for Chapter05/Taxi-v2-Q-network.py?

### ISSUE THREAD

**Issue by absoluterudi** [PacktPublishing/Hands-On-Q-Learning-with-Python#1]
Hello, 

great Book!

In Chapter05/Taxi-v2-Q-network.py there is an Agent Class which i don't find in OpenAI Gym 0.7.3 or tensorflow. 
So where can i find this class ?
Best 
Rudi

**Comment by habibdraft** [comment]
I defined it here. It hasn’t been updated in a while so there may be
issues. Everything is in the agents.py file.

https://github.com/habibdraft/RL-agents

**Comment by packt-irfaa** [comment]
Thank you @habibdraft I am closing the issue.
